"""跨端共享常量。"""

API_V1_PREFIX = "/api/v1"
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200

TIMEZONE = "Asia/Shanghai"
TRADE_DATE_FORMAT = "%Y-%m-%d"

MARKET_OPEN = "09:30"
MARKET_CLOSE = "15:00"

RETRY_MAX = 3
RETRY_BACKOFF_SECONDS = 5
